services:
  - type: web
    name: film-booking-app
    env: python
    buildCommand: |
      cd frontend
      npm install
      npm run build
      cd ..
      pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 8000
